### ISSUE TITLE
No link between tree and alignment if fasta header contains id and description

### ISSUE THREAD

**Issue by smoretti** [veidenberg/wasabi#1]
Hi

the link between tree leaves and fasta sequences is not done when the fasta header contains description (separated from the id by a space delimiter).

e.g.
```
>XXX description of XXX
```
does not link with XXX leaf in tree.

**Comment by veidenberg** [comment]
Please test the latest commit and let me know whether the issue is fixed.
I also updated Wasabi at http://wasabiapp.org

**Comment by smoretti** [comment]
I have now another issue linked to that one:

I have UniProt ids in my trees and alignments and they are now truncated.

E.g. XPC_MELGA becomes MELGA in tree viewer, and _MELGA is removed from alignment doing an error because lots of ids in that alignment start with XPC_.... and now lots of ids are duplicated according to Wasabi.

**Comment by veidenberg** [comment]
Forgot to check the order of parsing spaces vs underscores in fasta header.
Try the new commit (or wasabiapp.org:8000).

**Comment by smoretti** [comment]
It works with my toy example.

Will see with more examples.

Thanks
