### ISSUE TITLE
Online manual/tutorial

### ISSUE THREAD

**Issue by a1an77** [veidenberg/wasabi#12]
Is there an online manual or rather a tutorial for wasabi explaining its features and the tasks that one can perform with it? Some features are rather intuitive but others need a bit of clarification for the user.

**Comment by veidenberg** [comment]
The instructions on Wasabi homepage (http://wasabiapp.org) are not very detailed but the tutorial video and the info on the landing and about pages should give a good overview.
Which specific features (in need for clarification) did you have in mind?
Hint: icons and underlined words in Wasabi interface show help text on mouse hover.
