### ISSUE TITLE
PAGAN;   failed conversion using boost::any_cast

### ISSUE THREAD

**Issue by Ulisesrodr** [veidenberg/wasabi#16]
I'm using PAGAN to do a codon alignment with nucleotide sequences, but I`m get this messagge error, 

Computing BppDist guidetree for the initial alignment.terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> >'
  what():  boost::bad_any_cast: failed conversion using boost::any_cast
Abort trap: 6
I have a multifasta file with aprox 95 nucleotide sequences

**Comment by veidenberg** [comment]
Sorry for delayed reply. 
Please try running the alignment with the same input files with Pagan on the command line (http://wasabiapp.org/software) or send the input files to me (andres.veidenberg@helsinki.fi) so I could try myself and forward the issue to the developer of Pagan (Ari Löytynoja).
