### ISSUE TITLE
hidegaps not working when some sequences missing

### ISSUE THREAD

**Issue by a1an77** [veidenberg/wasabi#17]
When a tree is loaded which has more nodes than sequences in the fasta file a warning window appears asking to "delete all sequences", "prune empty leaves" or just go on ("ok" button).

If you just click on the ok button, the hide gaps tool is now broken. It should ignore the missing data columns instead and work as if they where not there at all.

Attached some sample files for reproducing (.txt suffix added to upload them)
[bug_hidegaps.fasta.txt](https://github.com/veidenberg/wasabi/files/2446889/bug_hidegaps.fasta.txt)
[bug_hidegaps.tree.txt](https://github.com/veidenberg/wasabi/files/2446890/bug_hidegaps.tree.txt)

**Comment by veidenberg** [comment]
I made tree leaf pruning automated, since leafs both with and without sequence break many functions. Wasabi is designed to work with paired tree+sequence data, or just the tree or sequence alignment separately, not with unpaired data.
