### ISSUE TITLE
prank -F and +F options

### ISSUE THREAD

**Issue by LiuKe98** [veidenberg/wasabi#22]
Hello eveyone,
     I'am aligning my protein sequences using prank. But when I was reading the document of the software prank, I was confused about the option of -F and +F. If I want to obtain a more accurate alignment result, which parameter should I choose, -F or +F ? And should I add the opetion '-protein' ?
Thanks in advance

**Comment by ariloytynoja** [comment]
Dear LiuKe, please have a look on the article that I sent you by email. BR, Ari
