### ISSUE TITLE
missing images in wasabiapp.org/software/prank/

### ISSUE THREAD

**Issue by matrs** [veidenberg/wasabi#26]
Hello, 
I don't know if this is the place to do this, but I'm gonna give it a try.  I was reading this page,  http://wasabiapp.org/software/prank/prank_differences/ , which is very informative but sadly all of the linked images are missing:
http://wasabiapp.org/download/data/topology1.png
http://wasabiapp.org/download/data/topology2.png
http://wasabiapp.org/download/data/subst_plots.png

That's it, hope somebody know where those images are :)

Cheers

**Comment by veidenberg** [comment]
Thanks for letting us know! The broken image links are now fixed.
