### ISSUE TITLE
External javascript libraries vulnerability

### ISSUE THREAD

**Issue by smoretti** [veidenberg/wasabi#27]
Hi

Wasabi contains external javascript libraries. Two of them have known vulnerabilities according to webhint:
- 'jQuery@3.2.1' has 3 known vulnerabilities (3 medium)
- 'Knockout@3.4.2' has 1 known vulnerability (1 medium)

Could you update Wasabi with the last version of both libraries?

See https://webhint.io/scanner/f9f46df1-28a2-4db6-8498-1a21217b0880#category-security
(I scanned http://was.bi/)

**Comment by veidenberg** [comment]
Hi @smoretti , thanks for the heads-up and sorry for the long delay. Libraries updated.
