### ISSUE TITLE
Load tree and msa files from 2 urls at the same time fails

### ISSUE THREAD

**Issue by smoretti** [veidenberg/wasabi#4]
I try to load a tree and an msa file at the same time following *http://wasabiapp.org/rest/* documentation but it fails.

It works perfectly with a single url=source but I cannot get two url sources loaded (tree and msa).
I tried with %26 and & but for both the import panel opens itself and runs indefinitely.

**Comment by veidenberg** [comment]
Failure to import from multiple url sources is a known bug.
Fix requires only minor code changes so look for a github push soon.


On 20 Nov 2017, at 14.16, smoretti <notifications@github.com<mailto:notifications@github.com>> wrote:


I try to load a tree and an msa file at the same time following http://wasabiapp.org/rest/ documentation but it fails.

It works perfectly with a single url=source but I cannot get two url sources loaded (tree and msa).
I tried with %26 and & but for both the import panel opens itself and runs indefinitely.

**Comment by smoretti** [comment]
Great!
Thanks

**Comment by veidenberg** [comment]
The latest commit should to fix it and import data from multiple url parameters (separated with '&').
If it doesn't work for you, add a comment with a pair of example URLs.

**Comment by smoretti** [comment]
It works for me with my toy example, url parameters separated with '&'.

I have just an empty error popup than opens itself when loading tree (Newick or NHX) and alignment (fasta) at the same time. See
![screenshot from 2017-11-27 13-15-58](https://user-images.githubusercontent.com/3072880/33266290-47b50af8-d375-11e7-9c64-923d2696d9d9.png)

Examples come from
- https://selectome.unil.ch/wwwtmp/ENSGT00390000005194/Euteleostomi/ENSGT00390000005194.Euteleostomi.001.aa_masked.fas
- https://selectome.unil.ch/wwwtmp/ENSGT00390000005194/Euteleostomi/ENSGT00390000005194.Euteleostomi.001.nwk

Firefox 57.0 (64 bits), Ubuntu xenial

**Comment by veidenberg** [comment]
No error on wasabiapp.org when loading these files. Also, the tree view should not cut out the 'XPC' prefix from leaf names.
Did you use the current version of the tree parser script (lib/jsphylosvg.rebuild.js)?

**Comment by smoretti** [comment]
I have the same error on my machine with Firefox and Chrome.
My local git repo is up-to-date.

The XPC prefix did not appear because I did the screenshot with the NHX tree, and the S tag (species) is displayed instead of the leaf label.

**Comment by veidenberg** [comment]
Can't reproduce with my local repo. I added a commit to mute empty error dialogs (console trace instead). Import from multiple urls seems to work.

**Comment by veidenberg** [comment]
Wasabi now imports from multiple urls.
