### ISSUE TITLE
Can't view an Ensembl alignment

### ISSUE THREAD

**Issue by muffato** [veidenberg/wasabi#7]
Hello,

I'm trying to view some alignments from Ensembl:
 - http://www.ensembl.org/Homo_sapiens/Gene/Family?g=ENSG00000139618;r=13:32315474-32400266
 - http://www.ensembl.org/Homo_sapiens/Gene/Compara_Tree?g=ENSG00000139618;r=13:32315474-32400266 (click on a node to see the link)
but the site hangs while loading the data.
There is the orange background, the acknowledgements and the three circles with alternating blue filling, and nothing. In the Javascript console there is this error:
```
wasabi.js:1045 Uncaught ReferenceError: touchHandler is not defined
    at Wasabi.w.init (wasabi.js:1045)
    at new Wasabi (wasabi.js:856)
    at onload (?wasabiURL=https%3A%2F%2Frest.ensembl.org%2Fgenetree%2Fid%2FENSGT00390000003602%3Fcontent-type%3Dtext%2Fjavascript%26aligned%3D1%26subtree_node_id%3D18887758%26:17)
w.init @ wasabi.js:1045
Wasabi @ wasabi.js:856
onload @ ?wasabiURL=https%3A%2F%2Frest.ensembl.org%2Fgenetree%2Fid%2FENSGT00390000003602%3Fcontent-type%3Dtext%2Fjavascript%26aligned%3D1%26subtree_node_id%3D18887758%26:17
```
(Chromium v65)
and
```
 [Show/hide message details.] ReferenceError: touchHandler is not defined[Learn More] wasabi.js:1045:448
w.init
http://wasabiapp.org/ensembl/wasabi.js:1045:448
Wasabi
http://wasabiapp.org/ensembl/wasabi.js:856:354
initTree
http://www.ensembl.org/wasabi/wasabi.htm:74:17
load/<
http://www.ensembl.org/wasabi/wasabi.htm:60:11
u
http://wasabiapp.org/ensembl/wasabi.js:73:130
fireWith
http://wasabiapp.org/ensembl/wasabi.js:74:430
d
http://wasabiapp.org/ensembl/wasabi.js:146:411
b/<
http://wasabiapp.org/ensembl/wasabi.js:157:1
```
(Firefox v61)

My laptop does have a touch-screen. Is it related ?

On my phone (Firefox on Android) it also hangs, although I don't even see the blue dots

**Comment by veidenberg** [comment]
The bug is now fixed, sorry for the long reponse time.
The bug only affected touch devices which used Ensembl desktop site (the above links direct touch devices to the mobile site by default, which omit the Genteree visualization/Wasabi links).

Since the Wasabi used in Ensembl visualizations is a specialized version with quite different codebase, please send future bug reports for that Wasabi directly via email (will also help with response times).

Andres
