### ISSUE TITLE
No download button when exporting subtree

### ISSUE THREAD

**Issue by a1an77** [veidenberg/wasabi#8]
With the demo dataset click on a tree node and select export subtree. The export window shows up without any option to download the tree as a file.
It should be possible to download the tree as a file instead.

**Comment by a1an77** [comment]
This issue still seems to be present in the online demo

**Comment by veidenberg** [comment]
Works for me (Firefox@http://wasabiapp.org:8000).

<img width="363" alt="subtree_export" src="https://user-images.githubusercontent.com/1215700/47440281-82022b00-d7b6-11e8-8a6a-b6e9e14f1375.png">

**Comment by a1an77** [comment]
Still not working for me, I suspect something is going wrong with the institute's cache since the local version from git works as expected.
